spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boss?useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
